import type { FC, PropsWithChildren, ReactNode } from "react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const Layout: FC<PropsWithChildren & { modal: ReactNode }> = ({
  children,
  modal,
}) => {
  return (
    <html lang="en">
      <body>
        {children}
        {modal}
      </body>
    </html>
  );
};

export default Layout;
