import type { FC, PropsWithChildren } from "react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const Layout: FC<PropsWithChildren> = ({ children }) => {
  return <>{children}</>;
};

export default Layout;
